#!/usr/bin/env python
# -*- coding: utf-8 -*-
""" Print beautiful JSON using Yayson"""
import sys
import json
import colorama
import argparse


def main():
    """ Main function """
    parser = argparse.ArgumentParser(
        description='Yayson produces beautiful JSON')
    parser.add_argument('-i', '--indent',
        type=int,
        default=4,
        help='Number of spaces to indent with (default: 4)')
    parser.add_argument('-s', '--sort',
        action='store_true',
        help='Turn on key sorting')
    args = parser.parse_args()

    # Initialize colorama
    colorama.init(autoreset=True)

    # Read the input
    doc = ''
    for line in sys.stdin.readlines():
        doc += line

    # Parse the JSON
    try:
        doc = json.loads(doc)
    except ValueError:
        sys.stderr.write('Invalid JSON\n')
        sys.exit(1)

    dump = json.dumps(
        doc,
        indent=args.indent,
        sort_keys=args.sort)

    # Print the JSON
    for line in dump.split('\n'):
        try:
            key, value = line.split(':', 1)
            value = value.strip()

            # Handle values
            if value[0] == '{':
                value = colorama.Fore.YELLOW + value
            if value[0] == '[':
                value = colorama.Fore.YELLOW + value
            elif value[0] == '"':
                value = colorama.Fore.MAGENTA + value
            else:
                value = colorama.Fore.CYAN + value
            if value[len(value)-1] == ',':
                value = (
                    colorama.Fore.MAGENTA + value[:len(value)-1] +
                    colorama.Fore.YELLOW + ','
                )

            print (colorama.Fore.YELLOW + key + ': ' + value)
        except ValueError:
            print(colorama.Fore.YELLOW + line)


if __name__ == '__main__':
    main()
    sys.exit(0)

sys.exit(1)
